version: '3.8'

services:
  db:
    image: postgres:15
    container_name: streaming_db
    restart: always
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=AT1-Api-em-flask-com-flasgger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Isso vai carregar o seu seed.sql automaticamente
      - ./src/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data: